version: "3.8"

services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - laravel_storage:/app/storage
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:LKaBX+ia5QhqS/pkQJi5W6mpsiQ0r7Ai79oWj+I+fh0=
      APP_URL: http://localhost:8080
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: secret
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  laravel_storage:
  db_data:
